active_modules:
  EvseSlac0:
    module: EvseSlac
    config_implementation:
      main:
        device: eth1
        evse_id: CHARGEBYTE_SAYS_HELLO
        nid: chargebyte!
        number_of_sounds: 10
    connections: {}
  api:
    module: API
    connections:
      evse_manager:
      - module_id: connector_1
        implementation_id: evse
  auth:
    module: Auth
    config_module:
      connection_timeout: 10
      prioritize_authorization_over_stopping_transaction: true
      selection_algorithm: PlugEvents
    connections:
      token_provider:
      - module_id: token_provider_1
        implementation_id: main
      token_validator:
      - module_id: token_validator
        implementation_id: main
      evse_manager:
      - module_id: connector_1
        implementation_id: evse
  cb_tarragon_driver:
    module: CbTarragonDriver
    connections: {}
  energy_manager:
    module: EnergyManager
    connections:
      energy_trunk:
      - module_id: grid_connection_point
        implementation_id: energy_grid
  connector_1:
    module: EvseManager
    config_module:
      ac_enforce_hlc: false
      ac_hlc_enabled: false
      ac_hlc_use_5percent: true
      ac_nominal_voltage: 230
      ac_with_soc: false
      charge_mode: AC
      connector_id: 1
      country_code: DE
      dbg_hlc_auth_after_tstep: false
      ev_receipt_required: false
      evse_id: DE*CHB*E123456*1
      has_ventilation: true
      max_current_import_A: 16
      payment_enable_contract: false
      payment_enable_eim: true
      rcd_enabled: true
      session_logging: false
      session_logging_path: /tmp/everest-logs
      session_logging_xml: false
      three_phases: true
    connections:
      bsp:
        - module_id: cb_tarragon_driver
          implementation_id: low_level
      slac:
        - module_id: EvseSlac0
          implementation_id: main
  grid_connection_point:
    module: EnergyNode
    config_module:
      fuse_limit_A: 63
      phase_count: 3
    connections:
      energy_consumer:
      - implementation_id: energy_grid
        module_id: connector_1
  token_provider_1:
    module: DummyTokenProvider
    config_implementation:
      main:
        timeout: 10
        token: DEADBEEF
        type: RFID
    connections:
      evse:
      - module_id: connector_1
        implementation_id: evse
  token_validator:
    module: DummyTokenValidator
    config_implementation:
      main:
        sleep: 0.25
        validation_reason: Token seems valid
        validation_result: Accepted
    connections: {}
x-module-layout: {}
