active_modules:
  api:
    module: API
    connections:
      evse_manager:
        - implementation_id: evse
          module_id: connector_1
      error_history:
        - module_id: error_history
          implementation_id: error_history
  error_history:
    module: ErrorHistory
    config_implementation:
      error_history:
        database_path: /tmp/error_history.db
  energy_manager:
    module: EnergyManager
    connections:
      energy_trunk:
        - implementation_id: energy_grid
          module_id: grid_connection_point
  connector_1:
    module: EvseManager
    config_module:
      connector_id: 1
      has_ventilation: true
      disable_authentication: true
    connections:
      bsp:
        - implementation_id: evse_board_support
          module_id: connector_1_powerpath
  grid_connection_point:
    module: EnergyNode
    config_module:
      fuse_limit_A: 16
      phase_count: 3
    connections:
      energy_consumer:
        - implementation_id: energy_grid
          module_id: connector_1
  connector_1_powerpath:
    module: CbCpxDriver
    config_module:
      can_interface: vcan0
      connector_type: IEC62196Type2Socket
      rcm_enable: false
      device_id: 1
